import type { RuntimeEnv } from "../runtime/env"
import type { LoadedWorkspace } from "../workspace/types"
import type { AppState } from "./app-state"
import { defaultIssuePageState, remoteSearchIssuePageSourceId } from "./issue-pages"

export function createInitialAppState(workspace: LoadedWorkspace, runtimeEnv: RuntimeEnv): AppState {
  return {
    runtimeEnv,
    route: "board",
    previousRoute: undefined,
    focusedPane: "main",
    jiraAuthReady: false,
    jiraProjectReady: false,
    workspaceLoading: false,
    workspaceLoadError: undefined,
    workspaceRequestId: 0,
    workspaceNotice: workspace.notice,
    authOnboarding: {
      open: false,
      step: "baseUrl",
      baseUrl: "",
      email: "",
      apiToken: "",
      saving: false,
    },
    projectPicker: {
      open: false,
      mode: "local",
      searchOpen: false,
      searchQuery: "",
      loading: false,
      saving: false,
      selectedIndex: 0,
      remoteBoardsByProject: {},
    },
    recentWorkspaces: [],
    sidebarSelectedIndex: 4,
    workspaceSelectedIndex: 0,
    workspaceFocusedArea: "cards",
    workspaceResultSelectedIndex: 0,
    commandPaletteOpen: false,
    commandPaletteQuery: "",
    commandPaletteSelectedIndex: 0,
    helpOpen: false,
    searchOpen: false,
    searchMode: "loaded",
    searchQuery: "",
    searchDraft: "",
    remoteSearchQuery: "",
    remoteSearchIssueKeys: [],
    remoteSearchPageState: defaultIssuePageState(remoteSearchIssuePageSourceId, 50),
    remoteSearchRequestId: 0,
    configSelectedSectionIndex: 0,
    configSelectedRowIndex: 0,
    configFocusedArea: "sections",
    configEditValue: "",
    configDraftCounter: 1,
    configDrafts: [],
    project: workspace.project,
    board: workspace.board,
    currentUser: workspace.currentUser,
    quickFilters: workspace.quickFilters,
    activeQuickFilters: [],
    activeSprintId: workspace.activeSprintId,
    sprints: workspace.sprints,
    statuses: workspace.statuses,
    issueTypes: workspace.issueTypes,
    columns: workspace.columns,
    issues: workspace.issues,
    activeSprintGroupBy: "none",
    kanbanGroupBy: "none",
    backlogGroupBy: "sprint",
    selectedBacklogGroupId: workspace.activeSprintId || "backlog",
    collapsedBacklogGroupIds: [],
    activeSprintStatusOffset: 0,
    kanbanStatusOffset: 0,
    selectedIssueKey: workspace.selectedIssueKey,
    selectedBoardLocations: {},
    inspectorSelectedFieldIndex: 1,
    inspectorEditValue: "",
    inspectorUserPicker: undefined,
    userDraftAccountIds: {},
    issueDrafts: {},
    commentDrafts: [],
    commentDraftCounter: 1,
    commentEditing: false,
    commentEditValue: "",
    rankDrafts: {},
    issueDeletes: [],
    issueDetailLoadingByKey: {},
    issueDetailErrorByKey: {},
    issueDetailLoadedAtByKey: {},
    issueDetailRequestId: 0,
    issuePageStateBySource: workspace.issuePageStateBySource,
    issueKeysBySource: workspace.issueKeysBySource,
    issuePageRequestIdBySource: {},
    projectListSelectedIssueKey: undefined,
    projectListHorizontalOffset: 0,
    projectListSort: "rank",
    timelineStartDateField: workspace.timelineStartDateField,
    timelineParentHydrationError: workspace.timelineParentHydrationError,
    timelineSelectedIssueKey: undefined,
    timelineWindowStart: utcToday(),
    timelineZoom: "week",
    collapsedTimelineParentKeys: [],
    pendingDeleteIssueKey: undefined,
    remoteApplyOpen: false,
    remoteApplyApplying: false,
    remoteDeleteConfirmationArmed: false,
    stagedDiscardOpen: false,
    stagedDiscardSelectedIndex: 0,
    stagedDiscardSelections: [],
    detailBodyEditing: false,
    detailBodyEditValue: "",
    draftIssueCounter: 1,
    stats: workspace.stats,
  }
}

function utcToday() {
  return new Date().toISOString().slice(0, 10)
}
